lakehouse:
  outputs:
    silver:
      dremio_space: lakehouse
      dremio_space_folder: silver
      object_storage_source: catalog
      object_storage_path: silver
      password: "{{ env_var('DREMIO_PASSWORD') }}"
      port: 9047
      software_host: 127.0.0.1
      threads: 1
      type: dremio
      use_ssl: false
      user: "{{ env_var('DREMIO_USER') }}"
    gold:
      dremio_space: lakehouse
      dremio_space_folder: gold
      object_storage_source: catalog
      object_storage_path: gold
      password: "{{ env_var('DREMIO_PASSWORD') }}"
      port: 9047
      software_host: 127.0.0.1
      threads: 1
      type: dremio
      use_ssl: false
      user: "{{ env_var('DREMIO_USER') }}"
  target: silver
    