version: 2

models:
  - name: customers
    description: "Transformed data for ecoride customers"
    columns:
      - name: id
        description: "Unique identifier for the customer"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "First name of the customer"
        tests:
          - not_null
      - name: email
        description: "Email address of the customer"
        tests:
          - not_null
          - unique

  - name: sales
    description: "Sales data for ecoride vehicles"
    columns:
      - name: id
        description: "Unique identifier for the sale transaction"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Identifier for the customer"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: id
    # Consider adding more specific tests if relevant for payment_method or sale_price.

  - name: vehicles
    description: "Details of ecoride vehicles"
    columns:
      - name: id
        description: "Unique identifier for the vehicle"
        tests:
          - not_null
          - unique
      - name: model_name
        description: "Name of the vehicle model"
        tests:
          - not_null
      - name: model_type
        description: "Type of the vehicle model, e.g., Sedan, SUV"
        tests:
          - not_null
          - accepted_values:
              values: ['Sedan', 'SUV', 'Crossover', 'Hatchback']
      - name: color
        description: "Color of the vehicle"
        tests:
          - not_null
      - name: year
        description: "Manufacturing year of the vehicle"
        tests:
          - not_null

  - name: product_reviews
    description: "Customer reviews for ecoride products"
    columns:
      - name: CustomerID
        description: "Identifier for the customer who wrote the review"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: id
      - name: ReviewID
        description: "Unique identifier for the product review"
        tests:
          - not_null
          - unique
      - name: VehicleModel
        description: "Model of the vehicle being reviewed"
        tests:
          - not_null
      - name: Rating
        description: "Rating given by the customer"
        tests:
          - not_null
      - name: Date
        description: "Date of the review"
        tests:
          - not_null

  - name: charging_sessions
    description: "Details of electric vehicle charging sessions"
    columns:
      - name: charging_rate
        description: "Rate of charging in kW"
        tests:
          - not_null
      - name: cost
        description: "Cost of the charging session"
        tests:
          - not_null
      - name: end_time
        description: "End time of the charging session"
        tests:
          - not_null
      - name: energy_consumed_kWh
        description: "Total energy consumed in kWh"
        tests:
          - not_null
      - name: id
        description: "Unique identifier for the charging session"
        tests:
          - not_null
          - unique
      - name: session_duration
        description: "Duration of the charging session in minutes"
        tests:
          - not_null
      - name: start_time
        description: "Start time of the charging session"
        tests:
          - not_null
      - name: station_id
        description: "Identifier of the charging station"
        tests:
          - not_null

  - name: stations
    description: "Details of electric vehicle charging stations"
    columns:
      - name: address
        description: "Address of the charging station"
        tests:
          - not_null
      - name: city
        description: "City where the charging station is located"
        tests:
          - not_null
      - name: country
        description: "Country where the charging station is located"
        tests:
          - not_null
      - name: id
        description: "Unique identifier for the charging station"
        tests:
          - not_null
          - unique
      - name: number_of_chargers
        description: "Number of chargers available at the station"
        tests:
          - not_null
      - name: operational_status
        description: "Current operational status of the station"
        tests:
          - not_null
      - name: state
        description: "State where the charging station is located"
        tests:
          - not_null
      - name: station_type
        description: "Type of the charging station"
        tests:
          - not_null

  - name: vehicle_health_logs
    description: "Log data for vehicle health and maintenance history"
    columns:
      - name: alerts
        description: "Alerts issued for the vehicle"
        tests: []
      - name: maintenance_history
        description: "History of maintenance activities"
        tests: []
      - name: manufacturing_year
        description: "Year the vehicle was manufactured"
        tests:
          - not_null
      - name: model
        description: "Model of the vehicle"
        tests:
          - not_null
      - name: vehicle_id
        description: "Unique identifier for the vehicle"
        tests:
          - not_null
          - unique
